### ISSUE TITLE
Dynamic Inventory Windows

### ISSUE THREAD

**Issue by eisiv** [tryfan/ansible-morpheus-collection#30]
Hi, James told me to just create an issue here.
It's regarding the suggested update for the dynamic inventory, and how it handles windows machines.
The update doesn't create any host groups when ran through Morpheus, but I could see it created host groups when testing with the inventory inside /var/tmp/ folder.

**Comment by tryfan** [comment]
Issue seems to be the hostvars are not being added to the inventory items.  Perhaps this never worked, but magically worked with linux.  Have to review how hostvars are added to the inventory items and work out a way to mock being in a morpheus environment for debugging purposes

**Comment by tryfan** [comment]
Please try [this file](https://github.com/tryfan/ansible-morpheus-collection/blob/option_rework/plugins/inventory/morpheus_inventory.py) in your environment, and let me know if it solves the problems.  I removed the old patch I put in, the issue turned out to be unimportant.  

This will work only with windows hosts with the agent installed and going over the command bus.

**Comment by eisiv** [comment]
It seems to be working great for both Linux and Windows now!

**Comment by tryfan** [comment]
That's great news!  I'll do some additional testing and cut a new release.

**Comment by tryfan** [comment]
0.1.5 has been released
